#!/bin/sh
#
#  script to find branch points and tips
#
awk 'BEGIN {
       maxnodes = 50000;
       for (i=0; i<maxnodes; i++) {
          isnode[i] = 0;
       }
       for (i=0; i<maxnodes; i++) {
          isparent[i] = 0;
       }
     }

     !/^#/ { 
	    node = $1; parent = $2; 
	    isnode[node] = 1;
	    isparent[parent]++;
	} 
      END {
            printf ("Branch points: \n");
            for (i=0; i<maxnodes; i++) {
		    if (isparent[i] > 1) { printf ("%4s ",i); } 
            }
            printf ("\n\n");
            printf ("Tips:  \n");
            for (i=0; i<maxnodes; i++) {
		    if (isnode[i] && isparent[i] == 0) { printf ("%4s ",i);}
            }
            printf ("\n");
      }
   ' $1
