#! /bin/sh -f
#
# nval_subcol
#  script to remove one column from nval.n
#
#  usage: nval_subcol 5 nval.n,  to remove column 5
#
awk "BEGIN {colnum = $1;}
      /^#/ && \$2!=\"xcone\" {print}
      /^#/ && \$2==\"xcone\" {
	                                     printf (\"#\"); 
	   for (i=2; i<colnum; i++)          printf (\"%8s\",\$i); 
	   if (colnum>0)                     printf (\"%8s\",\$i); 
	   for (i=colnum+2; i<=NF; i++)        printf (\"%8s\",\$i); 
	                                     printf (\" \n\"); 
      }
      \$1==\"xcone\" && \$2==\"xrod\" && \$3==\"hbat\" {
	                                     printf (\" \"); 
           ncells = NF-1; 
	   for (i=1; i<colnum; i++)          printf (\"%8s\",\$i); 
	  # if (colnum>0)                     printf (\"%8s\",\$i); 
	   for (i=colnum+1; i<=NF; i++)        printf (\"%8s\",\$i); 
	                                     printf (\" \n\"); 
	   }
   !/^#/ && !(\$1==\"xcone\" && \$2==\"xrod\") {
	   ce = match(\$0,\" _\");
           for (i=1; i<3; i++)  printf (\" \"); 
           for (i=1; i<colnum; i++)          printf (\"%7s \",\$i); 
          # if (colnum>0)                     printf (\"%7s \",\$(i)); 
           for (i=colnum+1; i<=ncells; i++)    printf (\"%7s \",\$i); 
	   print substr(\$0,ce-1)
	   }
    " $2

