#!/bin/sh
#
# printpeakdsiv
#
# $1=time, V=$35 (col 34 after time), Ca=$46, trace to find max
#
awk "BEGIN {

#       V  = 35;
      V  = 34;
      Ca = 46;
      peakv1=peakv2= -0.2;
      peakv1=peakv2= -0.2;
      peakc1=peakc2= 0;
      tpeakv1=tpeakv2=0;
      tpeakc1=tpeakc2=0;
      peak0Time=0.055;
      peak2Time=0.40;
      begin_line = 0;
      printf (\"%s: \",\"$1\");
     }
     
     "'/^#/   { if ($1 == "#e") {
		 endexp = $5;
	         peak2Time = endexp / 2;
		 begin_line = NR;
	      }
	    }
     /^#/ { 
        if (begin_line > 0) {
	    col_line = int((NR - begin_line)/3);
	    if ($1 == "#n" && col_line == (V-2)) recnod = substr($2,2,length($2)-2);
	}
     }
     $1==0.03 { peakv0 = $V; peakc0 = $Ca; }
     !/^#/ { 
	    if ($1<peak2Time) {
	        if (peakv1 < $V)  { peakv1 = $V;  tpeakv1 = $1; }
	        if (peakc1 < $Ca) { peakc1 = $Ca; tpeakc1 = $1; }
	    }
	    else {
	      if (NF >= 35) {
	        if (peakv2 < $V)  { peakv2 = $V;  tpeakv2 = $1; }
	        if (peakc2 < $Ca) { peakc2 = $Ca; tpeakc2 = $1; }
	      }
	    }
	  } 
	END {
	 # printf ("\n"); 
	 # printf ("Peakv0:  %-6.4g: %-9.4g  \n", peak0Time, peakv0); 
	 # printf ("Peakv1:  %-6.4g: %-9.4g  \n", tpeakv1, peakv1); 
	 # printf ("Peakv2:  %-6.4g: %-9.4g  \n", tpeakv2, peakv2); 
	 # printf ("Peakc0:  %-6.4g: %-9.4g  \n", peak0Time, peakc0); 
	 # printf ("Peakc1:  %-6.4g: %-9.4g  \n", tpeakc1, peakc1); 
	 # printf ("Peakc2:  %-6.4g: %-9.4g  \n", tpeakc2, peakc2); 
	 peakvh1 = peakv1 - peakv0;
	 peakvh2 = peakv2 - peakv0;
	 peakch1 = peakc1 - peakc0;
	 peakch2 = peakc2 - peakc0;
	 if (peakvh1==0 && peakvh2==0) peakvdiv = 1
         else                          peakvdiv = peakvh1;
	 if (peakch1==0 && peakch2==0) peakcdiv = 1
         else                          peakcdiv = peakch1;
	 printf ("%-13s V %-8.4g  DSI(V)  %-7.4g   Ca %-7.4g   DSI(Ca) %-7.4g\n", recnod,(peakvh1+peakvh2)*0.5,(peakvh1-peakvh2)/(peakvdiv), (peakch1+peakch2)*0.5,(peakch1-peakch2)/(peakcdiv)); 
	}
   ' $1
